### ISSUE TITLE
Sprachauswahl beim TTS

### ISSUE THREAD

**Issue by kjkriegel** [cascha42/funkzentrale#2]

**Comment by kjkriegel** [comment]
done in dd8d476

**Comment by cascha42** [comment]
- TTS Language Auswahl ohne Funktion, es wird immer Englisch abgespielt. Wenn Englisch ausgewählt wird, kommt ein Fehler.
- Deutsch sollte als vorausgewählte Sprache gesetzt werden

**Comment by kjkriegel** [comment]
Fixed those

**Comment by kjkriegel** [comment]
Still need to sort alphabeticaly
